version: "3"

rpc:
    enable: true
    listen: "tcp://127.0.0.1:6001"

server:
    command: "php app.php"
    relay: pipes

http:
    raw_body: true
    address: ${SERVER_HOST:-0.0.0.0}:${SERVER_PORT:-8080}
    middleware:
        - gzip
        - static
        - headers
        - http_metrics
    headers:
        response:
            Version: ${VERSION_TAG:-dev}
            Connection: "keep-alive"
        cors:
            allowed_origin: "*"
            allowed_headers: "*"
            allowed_methods: "GET,POST,PUT,DELETE"
            allow_credentials: true
            exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma,Version,Connection,Auth-Token"
            max_age: 600
    pool:
        num_workers: ${HTTP_NUM_WORKERS:-6}
        supervisor:
        max_worker_memory: 100
        debug: false
logs:
    mode: ${MODE:-development}
    # Logging level can be "panic", "error", "warn", "info", "debug".
    level: ${LOGS_LEVEL:-debug}
    # Encoding format can be "console" or "json" (last is preferred for production usage).
    encoding: ${LOGS_ENCODING:-console}

jobs:
    num_pollers: ${JOBS_NUM_POLLERS:-8}
    timeout: 60
    pool:
        num_workers: ${JOBS_NUM_WORKERS:-4}
        max_worker_memory: 100
        command: "php dispatcher/dispatcher.php"
    pipelines:
        user_parse_events:
            driver: memory
            config: {}
        user_parse_courses:
            driver: memory
            config: {}
        user_parse_grades:
            driver: memory
            config: {}
        notification_webhook:
            driver: memory
            config: {}
        user_set_initialized:
            driver: memory
            config: {}
        user_parse_assignments:
            driver: memory
            config: {}
        user_parse_courses_contents:
            driver: memory
            config: {}
    consume:
        [
            "user_parse_courses_contents",
            "user_parse_events",
            "user_parse_courses",
            "user_parse_grades",
            "notification_webhook",
            "user_set_initialized",
            'user_parse_assignments'
        ]

kv: 
    users:
        driver: memory
        config: {}
    lemmetization:
        driver: memory
        config: {}
service:
    kv_users_init:
        command: "php service/user_init.php"
    search_put_kv_lemmetization:
        command: "php service/load_lemetization.php"
    parse_user_courses_assignments:
        command: "php service/parse_user_courses_assignments.php"
        remain_after_exit: true
        restart_sec: 3600
    parse_users_events_grades:
        command: "php service/parse_users_events_grades.php"
        remain_after_exit: true
        restart_sec: 1800
#   parse_grades_users:
#       command: "php service/parse_grades_users.php"
#       remain_after_exit: true
#       restart_sec: 10
metrics:
    address: "${SERVER_HOST:-0.0.0.0}:2112"
