version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CRYPT_KEY: ${CRYPT_KEY} #Application secure key
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DRIVER: "mysql"
      DATABASE_HOST: "db"
      PASSWORD_SALT: ${PASSWORD_SALT} #Password salt
      RESEND_API_KEY: ${RESEND_API_KEY}
      MOODLE_WEBSERVICE_URL: ${MOODLE_WEBSERVICE_URL}
    command: sh -c "./vendor/bin/phinx migrate && ./rr serve -c .rr.yaml"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - app_data:/app
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME} #not root here
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 20
volumes:
  db_data:
  app_data:
