name: Release

on:
  push:
    branches:
      - main
permissions:
  contents: write 
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: php
          package-name: core
